#!/bin/bash

SOURCE_TOOL=$( ytools-query-directory-name --message "Please select an existing tool directory")
SOURCE_TOOL_NAME=$( basename "${SOURCE_TOOL}")
TARGET_TOOL_NAME=$( ytools-query-parameter --message "Please enter a new tool name" )

# Creating directories
for dir_name in $(find "${SOURCE_TOOL}" -type d -print); do
  target_dir_name=$( echo "${dir_name}" | sed "s/${SOURCE_TOOL_NAME}/${TARGET_TOOL_NAME}/g" )
  echo -n "Creating directory ${target_dir_name}: "
  mkdir -p "${target_dir_name}"
  if [ $? -eq 0 ]; then
    echo -e "\033[1;32mDone\033[0m"
  fi
done

# Creating files
for file_name in $(find "${SOURCE_TOOL}" -type f -print); do
  target_file_name=$( echo "${file_name}" | sed "s/${SOURCE_TOOL_NAME}/${TARGET_TOOL_NAME}/g" )
  echo -n "Creating file ${target_file_name}: "
  cp "${file_name}" "${target_file_name}"
  if [ $? -eq 0 ]; then
    echo -e "\033[1;32mDone\033[0m"
  fi
  # Patching files
  echo -n "Patching file ${target_file_name}: "
  sed -i "s/${SOURCE_TOOL_NAME}/${TARGET_TOOL_NAME}/g" "${target_file_name}"
  if [ $? -eq 0 ]; then
    echo -e "\033[1;32mDone\033[0m"
  fi

done


# Cloning documentation
for file_name in $(find "./doc" -type f -name "*${SOURCE_TOOL_NAME}*" -print); do
  target_file_name=$( echo "${file_name}" | sed "s/${SOURCE_TOOL_NAME}/${TARGET_TOOL_NAME}/g" )
  echo -n "Creating file ${target_file_name}: "
  cp "${file_name}" "${target_file_name}"
  if [ $? -eq 0 ]; then
    echo -e "\033[1;32mDone\033[0m"
  fi
  # Patching files
  echo -n "Patching file ${target_file_name}: "
  sed -i "s/${SOURCE_TOOL_NAME}/${TARGET_TOOL_NAME}/g" "${target_file_name}"
  if [ $? -eq 0 ]; then
    echo -e "\033[1;32mDone\033[0m"
  fi

done

# Fixing index.html
echo -n "Add link into index.html: "
sed -i "/<!-- Generator ID=HAQTer5632hg3 -->/i\              <li><a href=\"doc/${TARGET_TOOL_NAME}.html\">ytools-${TARGET_TOOL_NAME}</a> - this tool allow you to ...</li>" index.html
echo -e "\033[1;32mDone\033[0m"

# Fixing ytools.pro
echo -n "Add new project into ytools.pro: "
sed -i "/# Generator ID=Tnwbncdgye42376/a\    ${TARGET_TOOL_NAME} \x5C" ytools.pro
echo -e "\033[1;32mDone\033[0m"

# Fixing install script
echo -n "Add new tool into install script: "
sed -i "/# Generator ID=H7JndWqM8dghfgy/i\InstallTool \"${TARGET_TOOL_NAME}\"" install
echo -e "\033[1;32mDone\033[0m"
