#!/bin/bash
# This script will build and install ytools

# Author: Yuriy Lazutin
# Site: https://github.com/YuriyLazutin
# Location: Tomsk, Siberia
# Creation: 2021-jan-23
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

export YTOOLS_HOME="/opt/ytools"
export LBIN="/usr/local/bin"

# Create
#	.qmake.stash
#	Makefile
qmake ytools.pro -spec linux-g++

# Create
#	show-message/Makefile
make -f Makefile qmake_all

# Create
#	show-message/dialog.o
#	show-message/main.o
#	show-message/moc_dialog.cpp
#	show-message/moc_dialog.o
#	show-message/moc_predefs.h
#	show-message/show-message
#	query-file-name/dialog.o
#	query-file-name/main.o
#	query-file-name/moc_dialog.cpp
#	query-file-name/moc_dialog.o
#	query-file-name/moc_predefs.h
#	query-file-name/query-file-name
make -j8

sudo mkdir -p "${YTOOLS_HOME}"
sudo cp "query-directory-name/query-directory-name" "${YTOOLS_HOME}/query-directory-name"
sudo ln -s "${YTOOLS_HOME}/query-directory-name" "${LBIN}/ytools-query-directory-name"
sudo cp "query-file-name/query-file-name" "${YTOOLS_HOME}/query-file-name"
sudo ln -s "${YTOOLS_HOME}/query-file-name" "${LBIN}/ytools-query-file-name"
sudo cp "show-message/show-message" "${YTOOLS_HOME}/show-message"
sudo ln -s "${YTOOLS_HOME}/show-message" "${LBIN}/ytools-show-message"

