#!/bin/bash
# This script will build and install ytools

# Author: Yuriy Lazutin
# Site: https://github.com/YuriyLazutin
# Location: Tomsk, Siberia
# Creation: 2021-jan-23
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

YTOOLS_PREFIX="ytools-"
YTOOLS_HOME="/opt/ytools"
LBIN="/usr/local/bin"

function InstallTool {
  echo -n "Installing \"${1}\" into \"${YTOOLS_HOME}/${1}\": "
  sudo cp "${1}/${1}" "${YTOOLS_HOME}/${1}"
  if [ $? -eq 0 ]; then
    echo -e "\033[1;32mDone\033[0m"
  else
    echo -e "\033[1;31mFailed\033[0m"
  fi

  echo -n "Creating shortcut \"${LBIN}/${YTOOLS_PREFIX}${1}\": "
  sudo ln -s "${YTOOLS_HOME}/${1}" "${LBIN}/${YTOOLS_PREFIX}${1}"
  if [ $? -eq 0 ]; then
    echo -e "\033[1;32mDone\033[0m"
  else
    echo -e "\033[1;31mFailed\033[0m"
  fi
}


# Create
#	.qmake.stash
#	Makefile
qmake ytools.pro -spec linux-g++

# Create
#	{tool-name}/Makefile
make -f Makefile qmake_all

# Create moc files, compile to *.o and assemble to executables.
#	{tool-name}/*.o
#	{tool-name}/moc_*
#	{tool-name}/{tool-name}
make -j8

# Installation on host
sudo mkdir -p "${YTOOLS_HOME}"
InstallTool "query-directory-name"
InstallTool "query-file-name"
InstallTool "query-parameter"
InstallTool "query-password"
InstallTool "query-yesno"
InstallTool "show-message"
# Generator ID=H7JndWqM8dghfgy

ytools-show-message --message "YTools was installed successfully."
